name: Run tests

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['22.x']

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm install --ignore-scripts
        npx lerna run build --scope @eyevinn/web-player-core --scope @eyevinn/web-player-airplay --scope @eyevinn/web-player-debug
        npx lerna run build
        npm test

